import type { BlogPostSource } from "./blog";

// Generated by the content factory. Append posts between the sentinels only.
export const actualitePosts: BlogPostSource[] = [
  // ACTUALITE_GENERATED_START
  {
    slug: "glm-5-2-souverainete",
    date: "2026-06-18",
    author: "Paul Larmaraud",
    videoUrl:
      "https://dgjgscstyzcmtwgjrrda.supabase.co/storage/v1/object/public/artefacts/content/glm-5-2-souverainete-fr.mp4",
    translations: {
      fr: {
        title:
          "GLM-5.2 : la dépendance à l'IA américaine n'est déjà plus une fatalité",
        description:
          "Un labo chinois publie un modèle ouvert qui talonne Claude Opus 4.8 et bat GPT-5.5, six fois moins cher, sans restriction géographique. Analyse, chiffres, et comment l'utiliser.",
        category: "Actualité IA",
        readingTime: "6 min",
        content: `
      <p>Il y a un mois, les États-Unis ont suspendu l'accès européen à une série de modèles de pointe. Le signal était clair : ce que vous louez, on peut vous le retirer. Beaucoup y ont vu la preuve que l'Europe avait définitivement raté l'intelligence artificielle. Aujourd'hui, un événement nuance ce verdict.</p>
      <h2>Ce que Z.ai vient de publier</h2>
      <p>Le laboratoire chinois Z.ai a sorti GLM-5.2 : un modèle de 754 milliards de paramètres, dont 40 milliards activés par jeton. Deux choses le rendent remarquable, son niveau et sa licence.</p>
      <p>Le niveau : sur SWE-bench Pro, qui mesure la résolution de vrais tickets de code, il obtient 62,1, devant GPT-5.5 (58,6). Sur FrontierSWE, 74,4 %, au coude-à-coude avec Claude Opus 4.8 (75,1 %), le meilleur modèle propriétaire. Sur l'usage d'outils (MCP-Atlas), 77,0, juste derrière Opus 4.8 (77,8). Un modèle ouvert vient de rejoindre le peloton de tête.</p>
      <p>La licence : poids publiés en MIT, documentation précisant « aucune limite régionale ». Coût autour de 4,40 $ par million de jetons en sortie, environ six fois moins que ses rivaux fermés.</p>
      <h2>Pourquoi ce détail change tout</h2>
      <p>Le risque de départ était d'être coupé d'un fournisseur du jour au lendemain. Un modèle ouvert y répond directement : vous téléchargez les poids, vous l'exécutez sur votre infrastructure, la donnée ne sort jamais de chez vous, et personne ne peut révoquer votre accès. Ce qui faisait peur il y a un mois n'a plus de prise.</p>
      <p>Le laboratoire européen Pleias résumait bien le piège : « on ne loue pas un substrat pour appeler ça de la souveraineté ». C'est juste. Mais la conclusion habituelle, qu'il faudrait un champion européen sinon nous sommes perdus, passe à côté de l'essentiel. On peut posséder les poids. Et posséder un modèle quasi-frontière coûte désormais une fraction de ce qu'on imaginait.</p>
      <h2>Comment l'utiliser, concrètement</h2>
      <p>Trois chemins, du plus rapide au plus souverain.</p>
      <p><strong>Le tester en une ligne, via OpenRouter.</strong> Le modèle est exposé sous l'identifiant <code>z-ai/glm-5.2</code>. L'API est compatible OpenAI : vous changez l'URL de base et le nom du modèle, le reste de votre code ne bouge pas. Tarif : 1,40 $ par million de jetons en entrée, 4,40 $ en sortie, fenêtre de contexte d'un million de jetons.</p>
      <p><strong>Passer par l'éditeur, via l'API de Z.ai.</strong> Z.ai propose son propre accès hébergé, lui aussi compatible OpenAI.</p>
      <p><strong>L'héberger vous-même, pour la souveraineté.</strong> Les poids sont publics sur Hugging Face (<code>zai-org/GLM-5.2</code>, version FP8 d'environ 750 Go). On les sert avec vLLM ou SGLang sur ses propres serveurs (<code>vllm serve "zai-org/GLM-5.2-FP8" --tensor-parallel-size 8</code>). Une version GGUF permet même de le faire tourner sur une grosse station de travail. La donnée ne quitte jamais votre infrastructure.</p>
      <h2>La vision Parrit : agnostique par conception</h2>
      <p>C'est la posture que nous déployons chez nos clients. Nous ne parions pas sur un fournisseur, nous restons agnostiques : le bon modèle pour chaque tâche, la donnée qui reste chez le client, et la capacité de changer le jour où un meilleur sort. La semaine dernière, un modèle américain. Aujourd'hui, un modèle ouvert chinois. Demain, autre chose.</p>
      <p>Notre métier n'est pas de vous vendre un modèle, ni un slide. C'est de déployer la chose qui tourne, sur votre infrastructure, avec la liberté d'en changer le substrat sans tout casser. La vraie question pour un dirigeant n'est pas « qui fabrique le meilleur modèle », mais « savez-vous ce qui existe, et pouvez-vous en changer ».</p>
      <h2>Pour aller à la source</h2>
      <p><a href="https://venturebeat.com/technology/z-ais-open-weights-glm-5-2-beats-gpt-5-5-on-multiple-long-horizon-coding-benchmarks-for-1-6th-the-cost">VentureBeat</a> · <a href="https://openrouter.ai/z-ai/glm-5.2">OpenRouter</a> · <a href="https://huggingface.co/zai-org/GLM-5.2">Hugging Face</a> · <a href="https://pleias.ai/blog/fable-eu">Pleias</a></p>
    `,
      },
      en: {
        title:
          "GLM-5.2: dependence on American AI is already no longer inevitable",
        description:
          "A Chinese lab publishes an open model that comes close to Claude Opus 4.8 and beats GPT-5.5, six times cheaper, with no geographic restriction. Analysis, numbers, and how to use it.",
        category: "Actualité IA",
        readingTime: "6 min",
        content: `
      <p>A month ago, the United States suspended European access to a series of frontier models. The signal was clear: what you rent can be taken away. Many saw it as proof that Europe had definitively missed artificial intelligence. Today, one event qualifies that verdict.</p>
      <h2>What Z.ai just released</h2>
      <p>The Chinese lab Z.ai has released GLM-5.2: a 754-billion-parameter model, with 40 billion activated per token. Two things make it remarkable, its level and its license.</p>
      <p>The level: on SWE-bench Pro, which measures the resolution of real coding tickets, it scores 62.1, ahead of GPT-5.5 (58.6). On FrontierSWE, 74.4%, neck and neck with Claude Opus 4.8 (75.1%), the best proprietary model. On tool use (MCP-Atlas), 77.0, just behind Opus 4.8 (77.8). An open model has joined the leading pack.</p>
      <p>The license: weights published under MIT, documentation specifying "no regional restrictions". Cost around $4.40 per million output tokens, roughly six times less than its closed rivals.</p>
      <h2>Why this detail changes everything</h2>
      <p>The original risk was being cut off from a provider overnight. An open model answers that directly: you download the weights, run it on your infrastructure, the data never leaves your environment, and no one can revoke your access. What was frightening a month ago no longer has the same hold.</p>
      <p>The European lab Pleias summarized the trap well: "you do not rent a substrate and call it sovereignty". That is right. But the usual conclusion, that we need a European champion or we are lost, misses the essential point. You can own the weights. And owning a near-frontier model now costs a fraction of what we imagined.</p>
      <h2>How to use it, concretely</h2>
      <p>Three paths, from the fastest to the most sovereign.</p>
      <p><strong>Test it in one line, via OpenRouter.</strong> The model is exposed under the identifier <code>z-ai/glm-5.2</code>. The API is OpenAI-compatible: you change the base URL and the model name, the rest of your code does not move. Pricing: $1.40 per million input tokens, $4.40 for output, one-million-token context window.</p>
      <p><strong>Go through the publisher, via the Z.ai API.</strong> Z.ai offers its own hosted access, also OpenAI-compatible.</p>
      <p><strong>Host it yourself, for sovereignty.</strong> The weights are public on Hugging Face (<code>zai-org/GLM-5.2</code>, FP8 version of about 750 GB). You serve them with vLLM or SGLang on your own servers (<code>vllm serve "zai-org/GLM-5.2-FP8" --tensor-parallel-size 8</code>). A GGUF version even makes it possible to run it on a large workstation. The data never leaves your infrastructure.</p>
      <h2>The Parrit vision: agnostic by design</h2>
      <p>That is the posture we deploy with our clients. We do not bet on one provider, we stay agnostic: the right model for each task, data that stays with the client, and the ability to switch the day a better one comes out. Last week, an American model. Today, an open Chinese model. Tomorrow, something else.</p>
      <p>Our job is not to sell you a model, nor a slide. It is to deploy the thing that runs, on your infrastructure, with the freedom to change the substrate without breaking everything. The real question for an executive is not "who makes the best model", but "do you know what exists, and can you switch".</p>
      <h2>Go to the source</h2>
      <p><a href="https://venturebeat.com/technology/z-ais-open-weights-glm-5-2-beats-gpt-5-5-on-multiple-long-horizon-coding-benchmarks-for-1-6th-the-cost">VentureBeat</a> · <a href="https://openrouter.ai/z-ai/glm-5.2">OpenRouter</a> · <a href="https://huggingface.co/zai-org/GLM-5.2">Hugging Face</a> · <a href="https://pleias.ai/blog/fable-eu">Pleias</a></p>
    `,
      },
      "pt-BR": {
        title:
          "GLM-5.2: a dependência da IA americana já não é mais uma fatalidade",
        description:
          "Um laboratório chinês publica um modelo aberto que encosta no Claude Opus 4.8 e supera o GPT-5.5, seis vezes mais barato, sem restrição geográfica. Análise, números e como usar.",
        category: "Actualité IA",
        readingTime: "6 min",
        content: `
      <p>Há um mês, os Estados Unidos suspenderam o acesso europeu a uma série de modelos de ponta. O sinal era claro: aquilo que você aluga pode ser retirado. Muitos viram nisso a prova de que a Europa tinha perdido definitivamente a inteligência artificial. Hoje, um evento relativiza esse veredito.</p>
      <h2>O que a Z.ai acaba de publicar</h2>
      <p>O laboratório chinês Z.ai lançou o GLM-5.2: um modelo de 754 bilhões de parâmetros, dos quais 40 bilhões são ativados por token. Duas coisas o tornam notável, seu nível e sua licença.</p>
      <p>O nível: no SWE-bench Pro, que mede a resolução de tickets reais de código, ele obtém 62,1, à frente do GPT-5.5 (58,6). No FrontierSWE, 74,4%, lado a lado com o Claude Opus 4.8 (75,1%), o melhor modelo proprietário. No uso de ferramentas (MCP-Atlas), 77,0, logo atrás do Opus 4.8 (77,8). Um modelo aberto acaba de entrar no pelotão de frente.</p>
      <p>A licença: pesos publicados em MIT, documentação especificando "sem limites regionais". Custo em torno de US$ 4,40 por milhão de tokens de saída, cerca de seis vezes menos que seus rivais fechados.</p>
      <h2>Por que esse detalhe muda tudo</h2>
      <p>O risco inicial era ser cortado de um fornecedor de um dia para o outro. Um modelo aberto responde diretamente a isso: você baixa os pesos, executa na sua infraestrutura, os dados nunca saem da sua casa, e ninguém pode revogar seu acesso. O que assustava há um mês já não tem o mesmo poder.</p>
      <p>O laboratório europeu Pleias resumiu bem a armadilha: "não se aluga um substrato para chamar isso de soberania". Está certo. Mas a conclusão habitual, de que precisaríamos de um campeão europeu ou estaríamos perdidos, deixa passar o essencial. É possível possuir os pesos. E possuir um modelo quase fronteira agora custa uma fração do que imaginávamos.</p>
      <h2>Como usar, concretamente</h2>
      <p>Três caminhos, do mais rápido ao mais soberano.</p>
      <p><strong>Testar em uma linha, via OpenRouter.</strong> O modelo está exposto sob o identificador <code>z-ai/glm-5.2</code>. A API é compatível com OpenAI: você muda a URL base e o nome do modelo, o restante do seu código não se move. Preço: US$ 1,40 por milhão de tokens de entrada, US$ 4,40 na saída, janela de contexto de um milhão de tokens.</p>
      <p><strong>Passar pelo editor, via API da Z.ai.</strong> A Z.ai oferece seu próprio acesso hospedado, também compatível com OpenAI.</p>
      <p><strong>Hospedar você mesmo, pela soberania.</strong> Os pesos são públicos no Hugging Face (<code>zai-org/GLM-5.2</code>, versão FP8 de cerca de 750 GB). Eles são servidos com vLLM ou SGLang nos seus próprios servidores (<code>vllm serve "zai-org/GLM-5.2-FP8" --tensor-parallel-size 8</code>). Uma versão GGUF permite até rodá-lo em uma workstation robusta. Os dados nunca saem da sua infraestrutura.</p>
      <h2>A visão Parrit: agnóstica por concepção</h2>
      <p>Essa é a postura que implantamos nos nossos clientes. Não apostamos em um fornecedor, permanecemos agnósticos: o modelo certo para cada tarefa, os dados que ficam com o cliente, e a capacidade de mudar no dia em que surgir algo melhor. Na semana passada, um modelo americano. Hoje, um modelo chinês aberto. Amanhã, outra coisa.</p>
      <p>Nosso trabalho não é vender um modelo, nem um slide. É implantar a coisa que roda, na sua infraestrutura, com a liberdade de trocar o substrato sem quebrar tudo. A verdadeira pergunta para um dirigente não é "quem fabrica o melhor modelo", mas "você sabe o que existe, e consegue mudar".</p>
      <h2>Ir à fonte</h2>
      <p><a href="https://venturebeat.com/technology/z-ais-open-weights-glm-5-2-beats-gpt-5-5-on-multiple-long-horizon-coding-benchmarks-for-1-6th-the-cost">VentureBeat</a> · <a href="https://openrouter.ai/z-ai/glm-5.2">OpenRouter</a> · <a href="https://huggingface.co/zai-org/GLM-5.2">Hugging Face</a> · <a href="https://pleias.ai/blog/fable-eu">Pleias</a></p>
    `,
      },
    },
  },
  // ACTUALITE_GENERATED_END
];
