import type { BlogPostSource } from "./blog";

// Generated by the daily blog engine. Keep this file as the only write target.
export const generatedBlogPosts: BlogPostSource[] = [
  {
    slug: "une-carte-une-action",
    date: "2026-06-17",
    publishedAt: "2026-06-17",
    author: "Paul Larmaraud",
    tags: ["operating-system", "automation", "trust"],
    relatedSlugs: [
      "le-brouillon-qui-sait-se-taire",
      "le-bon-endroit-pour-ecrire",
    ],
    translations: {
      fr: {
        title: "Une carte, une action",
        description:
          "Dans un poste de pilotage interne, une carte validée ne doit pas seulement changer de statut. Elle doit exécuter l'action promise.",
        category: "Façon de travailler",
        readingTime: "4 min",
        content: `
      <p>Sur un poste de pilotage interne, l'opérateur fait défiler des fiches. Chaque fiche porte une décision : relancer ce contact, envoyer cette proposition, marquer ce dossier comme traité. Un geste vers la droite veut dire : oui, fais-le.</p>
      <p>Pendant plusieurs semaines, ce geste n'a rien fait. Il changeait une ligne de statut en base. L'action promise ne partait jamais.</p>
      <h2>Un écart invisible et coûteux</h2>
      <p>En surface, tout fonctionnait. La fiche passait au vert, la liste avançait, le tableau de bord donnait l'impression d'un système vivant. Le problème était plus bas : la relance n'était pas partie, mais rien ne le signalait.</p>
      <p>Ce genre d'écart est dangereux parce qu'il ne ressemble pas à une panne. Une panne bloque. Ici, le système continue. Il ment calmement.</p>
      <p>Le coût n'est pas dans le code. Il est dans la confiance accordée à un outil qui dit avoir agi.</p>
      <h2>La règle gravée</h2>
      <p>Une carte égale une action égale un geste. Valider une fiche ne change pas un statut. Valider une fiche exécute la chose.</p>
      <p>Si l'action ne peut pas partir, la carte doit rester ouverte. Si le canal est indisponible, la carte doit le dire. Si une validation humaine manque, elle doit rester visible. Le système n'a pas le droit de dire c'est fait tant que ce n'est pas fait.</p>
      <h2>Pourquoi cette discipline tient</h2>
      <p>Un poste de pilotage ne vaut pas par le nombre de boutons qu'il affiche. Il vaut par la correspondance stricte entre une intention humaine et un effet réel dans le système.</p>
      <p>Cette règle paraît étroite. Elle évite pourtant une dérive classique : construire des interfaces de décision qui ne sont que des écrans de décoration posés sur des scripts séparés.</p>
      <p>Un geste qui ne fait rien est un mensonge. Un statut vert sans effet aval aussi.</p>
    `,
      },
      en: {
        title: "One card, one action",
        description:
          "In an internal cockpit, approving a card must not only change a status. It must execute the promised action.",
        category: "How We Work",
        readingTime: "4 min",
        content: `
      <p>In an internal cockpit, the operator reviews cards. Each card carries a decision: follow up with this contact, send this proposal, mark this file as handled. A swipe to the right means: yes, do it.</p>
      <p>For several weeks, that gesture did nothing. It changed a status row in the database. The promised action never happened.</p>
      <h2>An invisible and expensive gap</h2>
      <p>On the surface, everything worked. The card turned green, the list moved forward, the dashboard looked alive. The problem was lower down: the follow-up had not been sent, and nothing said so.</p>
      <p>This kind of gap is dangerous because it does not look like a failure. A failure blocks. Here, the system keeps moving. It lies quietly.</p>
      <p>The cost is not in the code. It is in the trust granted to a tool that says it has acted.</p>
      <h2>The rule</h2>
      <p>One card equals one action equals one gesture. Approving a card does not change a status. Approving a card executes the thing.</p>
      <p>If the action cannot run, the card must remain open. If the channel is unavailable, the card must say so. If a human approval is missing, it must stay visible. The system is not allowed to say done until it is done.</p>
      <h2>Why the rule holds</h2>
      <p>A cockpit is not valuable because it displays many buttons. It is valuable because there is a strict correspondence between a human intention and a real effect in the system.</p>
      <p>The rule sounds narrow. It prevents a common drift: building decision interfaces that are only decorative screens on top of disconnected scripts.</p>
      <p>A gesture that does nothing is a lie. A green status without a downstream effect is one too.</p>
    `,
      },
      "pt-BR": {
        title: "Um cartão, uma ação",
        description:
          "Em um painel interno, aprovar um cartão não deve apenas mudar um status. Deve executar a ação prometida.",
        category: "Forma de trabalhar",
        readingTime: "4 min",
        content: `
      <p>Em um painel interno, o operador passa por cartões. Cada cartão traz uma decisão: retomar contato com esta pessoa, enviar esta proposta, marcar este dossiê como tratado. Um gesto para a direita significa: sim, faça.</p>
      <p>Durante várias semanas, esse gesto não fez nada. Ele mudava uma linha de status no banco. A ação prometida nunca acontecia.</p>
      <h2>Um desvio invisível e caro</h2>
      <p>Na superfície, tudo funcionava. O cartão ficava verde, a lista avançava, o painel parecia vivo. O problema estava mais abaixo: a retomada de contato não tinha sido enviada, mas nada indicava isso.</p>
      <p>Esse tipo de desvio é perigoso porque não parece uma pane. Uma pane bloqueia. Aqui, o sistema continua. Ele mente em silêncio.</p>
      <p>O custo não está no código. Está na confiança concedida a uma ferramenta que diz ter agido.</p>
      <h2>A regra</h2>
      <p>Um cartão equivale a uma ação e a um gesto. Aprovar um cartão não muda um status. Aprovar um cartão executa a coisa.</p>
      <p>Se a ação não puder rodar, o cartão deve continuar aberto. Se o canal estiver indisponível, o cartão deve dizer isso. Se faltar uma validação humana, ela deve permanecer visível. O sistema não tem o direito de dizer feito enquanto não estiver feito.</p>
      <h2>Por que a regra se sustenta</h2>
      <p>Um painel não vale pelo número de botões que exibe. Ele vale pela correspondência estrita entre uma intenção humana e um efeito real no sistema.</p>
      <p>A regra parece estreita. Ela evita uma deriva comum: construir interfaces de decisão que são apenas telas decorativas sobre scripts desconectados.</p>
      <p>Um gesto que não faz nada é uma mentira. Um status verde sem efeito a jusante também.</p>
    `,
      },
    },
  },
  {
    slug: "le-brouillon-qui-sait-se-taire",
    date: "2026-06-17",
    publishedAt: "2026-06-17",
    author: "Paul Larmaraud",
    tags: ["editorial-system", "quality-gate", "automation"],
    relatedSlugs: [
      "une-carte-une-action",
      "le-bon-endroit-pour-ecrire",
    ],
    translations: {
      fr: {
        title: "Le brouillon qui sait se taire",
        description:
          "Un moteur éditorial utile ne force pas une publication quotidienne. Il sait reconnaître les jours où la matière ne mérite pas d'article.",
        category: "Façon de travailler",
        readingTime: "4 min",
        content: `
      <p>Un système de publication interne peut facilement devenir une machine à remplir un calendrier. Il collecte des commits, des notes, des décisions, puis fabrique un texte parce que la journée doit produire quelque chose.</p>
      <p>C'est exactement le piège. Le calendrier devient la source. L'activité réelle devient un prétexte.</p>
      <h2>La bonne unité n'est pas le jour</h2>
      <p>Le jour est une fenêtre de collecte. Ce n'est pas une obligation éditoriale.</p>
      <p>Un bon brouillon part d'un événement fermé : un bug corrigé en production, une règle opératoire clarifiée, un deal livré, une décision devenue code. Sans événement fermé, il n'y a pas d'article. Il y a seulement du commentaire.</p>
      <h2>Le filtre avant la plume</h2>
      <p>Le moteur doit donc savoir refuser. Pas de matière forte. Pas d'article. Matière forte mais non anonymisable. Pas d'article. Matière réelle mais incompréhensible pour un dirigeant non technicien. Pas d'article.</p>
      <p>La sortie utile n'est pas toujours un texte. Certains jours, la meilleure sortie est le silence.</p>
      <h2>Ce que le silence protège</h2>
      <p>Il protège la confiance du lecteur. Il protège aussi l'équipe contre une dérive plus insidieuse : transformer chaque micro-activité en preuve publique.</p>
      <p>Une cadence honnête peut produire trois à cinq textes par semaine dans une période dense. Elle peut aussi produire zéro texte pendant deux jours si rien n'est assez net.</p>
      <p>La discipline n'est pas de publier souvent. La discipline est de ne publier que lorsque le travail a laissé une trace qui mérite d'être comprise.</p>
    `,
      },
      en: {
        title: "The draft that knows when to stay silent",
        description:
          "A useful editorial system does not force a daily post. It knows when the raw material does not deserve an article.",
        category: "How We Work",
        readingTime: "4 min",
        content: `
      <p>An internal publishing system can easily become a calendar-filling machine. It collects commits, notes, decisions, then produces a text because the day is supposed to produce something.</p>
      <p>That is the trap. The calendar becomes the source. Real activity becomes a pretext.</p>
      <h2>The right unit is not the day</h2>
      <p>A day is a collection window. It is not an editorial obligation.</p>
      <p>A good draft starts from a closed event: a bug fixed in production, an operating rule clarified, a delivered project, a decision turned into code. Without a closed event, there is no article. There is only commentary.</p>
      <h2>The filter before the pen</h2>
      <p>The system must know how to refuse. No strong material. No article. Strong material but impossible to anonymize. No article. Real material but unreadable for a non-technical executive. No article.</p>
      <p>The useful output is not always a text. On some days, the useful output is silence.</p>
      <h2>What silence protects</h2>
      <p>It protects the reader's trust. It also protects the team from a more subtle drift: turning every micro-activity into public proof.</p>
      <p>An honest cadence can produce three to five texts per week during a dense period. It can also produce zero texts for two days if nothing is clear enough.</p>
      <p>The discipline is not to publish often. The discipline is to publish only when the work has left a trace worth understanding.</p>
    `,
      },
      "pt-BR": {
        title: "O rascunho que sabe ficar em silêncio",
        description:
          "Um sistema editorial útil não força uma publicação diária. Ele sabe reconhecer quando a matéria-prima não merece um artigo.",
        category: "Forma de trabalhar",
        readingTime: "4 min",
        content: `
      <p>Um sistema interno de publicação pode virar facilmente uma máquina de preencher calendário. Ele coleta commits, notas, decisões e produz um texto porque o dia deveria produzir alguma coisa.</p>
      <p>Esse é o erro. O calendário vira a fonte. A atividade real vira pretexto.</p>
      <h2>A unidade certa não é o dia</h2>
      <p>O dia é uma janela de coleta. Não é uma obrigação editorial.</p>
      <p>Um bom rascunho começa por um evento fechado: uma falha corrigida em produção, uma regra operacional esclarecida, uma entrega concluída, uma decisão transformada em código. Sem evento fechado, não há artigo. Há apenas comentário.</p>
      <h2>O filtro antes da escrita</h2>
      <p>O sistema precisa saber recusar. Sem matéria forte. Sem artigo. Matéria forte, mas impossível de anonimizar. Sem artigo. Matéria real, mas ilegível para um dirigente não técnico. Sem artigo.</p>
      <p>A saída útil nem sempre é um texto. Em alguns dias, a melhor saída é o silêncio.</p>
      <h2>O que o silêncio protege</h2>
      <p>Ele protege a confiança do leitor. Também protege a equipe contra uma deriva mais sutil: transformar cada microatividade em prova pública.</p>
      <p>Uma cadência honesta pode produzir três a cinco textos por semana em um período denso. Também pode produzir zero texto durante dois dias se nada estiver suficientemente claro.</p>
      <p>A disciplina não é publicar muito. A disciplina é publicar apenas quando o trabalho deixou um rastro que merece ser compreendido.</p>
    `,
      },
    },
  },
  {
    slug: "le-bon-endroit-pour-ecrire",
    date: "2026-06-17",
    publishedAt: "2026-06-17",
    author: "Paul Larmaraud",
    tags: ["software-design", "publishing", "maintenance"],
    relatedSlugs: [
      "une-carte-une-action",
      "le-brouillon-qui-sait-se-taire",
    ],
    translations: {
      fr: {
        title: "Le bon endroit pour écrire",
        description:
          "Avant d'automatiser une publication, il faut choisir un point d'écriture stable. Sinon le moteur devient un risque de maintenance.",
        category: "Façon de travailler",
        readingTime: "4 min",
        content: `
      <p>Avant de brancher un moteur éditorial sur un site, une question paraît secondaire : où le moteur a-t-il le droit d'écrire ?</p>
      <p>La mauvaise réponse est tentante. Le script ouvre le fichier principal du blog, cherche le tableau des articles, injecte un bloc au bon endroit, puis espère que la structure n'aura pas changé. Cela fonctionne une fois. Ensuite, chaque refonte devient un risque.</p>
      <h2>Le fichier principal n'est pas une API</h2>
      <p>Un fichier lu par des humains n'est pas forcément un point d'entrée pour une machine. S'il contient les articles historiques, les types, les fonctions de tri et la logique de publication, le modifier automatiquement revient à confondre une page de travail avec une interface stable.</p>
      <p>La règle est simple : le moteur écrit dans un fichier dédié. Le site lit ce fichier et le combine avec les articles existants.</p>
      <h2>Ce que cette séparation évite</h2>
      <p>Elle évite les modifications fragiles. Elle évite les insertions au mauvais endroit. Elle évite surtout qu'un outil de publication ait le pouvoir de casser la logique historique du blog.</p>
      <p>Le code principal reste un code de lecture. Le fichier généré devient le seul point d'écriture. La frontière est visible dans le dépôt et vérifiable en revue.</p>
      <h2>La maintenance comme preuve de sérieux</h2>
      <p>Ce détail ne se voit pas dans l'article publié. Il se voit six semaines plus tard, quand il faut changer la page blog sans relire un script d'injection.</p>
      <p>Une automatisation fiable commence souvent par ce genre de décision étroite : donner à la machine un couloir précis, puis lui interdire le reste.</p>
      <p>Le bon système n'est pas celui qui peut écrire partout. C'est celui qui sait exactement où il a le droit d'écrire.</p>
    `,
      },
      en: {
        title: "The right place to write",
        description:
          "Before automating publication, choose a stable write target. Otherwise the engine becomes a maintenance risk.",
        category: "How We Work",
        readingTime: "4 min",
        content: `
      <p>Before connecting an editorial engine to a website, one question looks secondary: where is the engine allowed to write?</p>
      <p>The wrong answer is tempting. The script opens the main blog file, finds the post array, injects a block in the right place, then hopes the structure will not change. It works once. After that, every redesign becomes a risk.</p>
      <h2>The main file is not an API</h2>
      <p>A file read by humans is not automatically a machine entry point. If it contains historical articles, types, sorting functions and publishing logic, editing it automatically confuses a working page with a stable interface.</p>
      <p>The rule is simple: the engine writes to a dedicated file. The site reads that file and combines it with the existing articles.</p>
      <h2>What the separation prevents</h2>
      <p>It prevents fragile edits. It prevents insertions in the wrong place. Most importantly, it prevents a publishing tool from having the power to break the historical blog logic.</p>
      <p>The main code remains reading code. The generated file becomes the only write target. The boundary is visible in the repository and verifiable during review.</p>
      <h2>Maintenance as proof of seriousness</h2>
      <p>This detail is invisible in the published article. It becomes visible six weeks later, when the blog page changes without anyone having to reread an injection script.</p>
      <p>Reliable automation often starts with this kind of narrow decision: give the machine a precise corridor, then forbid the rest.</p>
      <p>The right system is not the one that can write everywhere. It is the one that knows exactly where it is allowed to write.</p>
    `,
      },
      "pt-BR": {
        title: "O lugar certo para escrever",
        description:
          "Antes de automatizar uma publicação, é preciso escolher um ponto de escrita estável. Caso contrário, o motor vira um risco de manutenção.",
        category: "Forma de trabalhar",
        readingTime: "4 min",
        content: `
      <p>Antes de conectar um motor editorial a um site, uma pergunta parece secundária: onde o motor tem permissão para escrever?</p>
      <p>A resposta errada é tentadora. O script abre o arquivo principal do blog, encontra a lista de artigos, injeta um bloco no lugar certo e espera que a estrutura não mude. Funciona uma vez. Depois disso, cada redesenho vira um risco.</p>
      <h2>O arquivo principal não é uma API</h2>
      <p>Um arquivo lido por humanos não é automaticamente um ponto de entrada para uma máquina. Se ele contém artigos históricos, tipos, funções de ordenação e lógica de publicação, editá-lo automaticamente confunde uma página de trabalho com uma interface estável.</p>
      <p>A regra é simples: o motor escreve em um arquivo dedicado. O site lê esse arquivo e o combina com os artigos existentes.</p>
      <h2>O que essa separação evita</h2>
      <p>Ela evita edições frágeis. Evita inserções no lugar errado. Sobretudo, evita que uma ferramenta de publicação tenha poder para quebrar a lógica histórica do blog.</p>
      <p>O código principal continua sendo código de leitura. O arquivo gerado vira o único ponto de escrita. A fronteira fica visível no repositório e verificável na revisão.</p>
      <h2>A manutenção como prova de seriedade</h2>
      <p>Esse detalhe não aparece no artigo publicado. Ele aparece seis semanas depois, quando é preciso mudar a página do blog sem reler um script de injeção.</p>
      <p>Uma automação confiável costuma começar por esse tipo de decisão estreita: dar à máquina um corredor preciso e proibir o resto.</p>
      <p>O bom sistema não é o que pode escrever em qualquer lugar. É o que sabe exatamente onde tem permissão para escrever.</p>
    `,
      },
    },
  },
];
